"""
inter_channel_cosines.py — pairwise cosines between every pair of CAA channels.

Produces an N×N cosine matrix per layer for the channels passed in. This is the
quantitative grounding for the "non-orthogonality blunts multi-channel
composition" hypothesis explored in the substrate paper (W7-W8).

USAGE:
  python3 infra/steering-vectors/inter_channel_cosines.py \\
      --channels cheerfulness,sociability,achievement_striving,stimulation,\\
                 dospert_financial,dospert_recreational,self_direction,\\
                 cautiousness,conscientiousness_self_discipline_v3 \\
      --out infra/steering-vectors/inter-channel-cosines-2026-05-08.md

Emits markdown: per-layer matrix + flat sorted list of largest-overlap pairs.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_VECTORS_DIR = REPO_ROOT / "infra" / "steering-vectors" / "qwen2.5-7b-instruct"


def cosine(a, b) -> float:
    return float((a @ b) / (a.norm() * b.norm() + 1e-9))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--channels", required=True,
                    help="Comma-separated channel names")
    ap.add_argument("--vectors-dir", type=Path, default=DEFAULT_VECTORS_DIR)
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument("--layer", type=int, default=None,
                    help="Optionally restrict to a single layer (default: all layers)")
    args = ap.parse_args()

    try:
        import torch
    except ImportError:
        print("ERROR: torch required", file=sys.stderr)
        return 2

    channels = [c.strip() for c in args.channels.split(",") if c.strip()]
    if len(channels) < 2:
        print("ERROR: need at least 2 channels", file=sys.stderr)
        return 2

    # Load all channel vectors
    vectors = {}
    for ch in channels:
        path = args.vectors_dir / ch / "vector.pt"
        if not path.exists():
            print(f"WARNING: skipping {ch} — no vector at {path}", file=sys.stderr)
            continue
        v = torch.load(path, map_location="cpu", weights_only=False)
        if not isinstance(v, dict):
            print(f"WARNING: skipping {ch} — not a dict", file=sys.stderr)
            continue
        vectors[ch] = v

    available = list(vectors.keys())
    if not available:
        print("ERROR: no vectors loaded", file=sys.stderr)
        return 2

    # Determine common layers
    layer_sets = [set(v.keys()) for v in vectors.values()]
    common_layers = sorted(set.intersection(*layer_sets))
    if args.layer is not None:
        common_layers = [args.layer] if args.layer in common_layers else []
    if not common_layers:
        print("ERROR: no common layers across channels", file=sys.stderr)
        return 2

    lines = [
        "# Inter-channel cosine matrix",
        "",
        "_Generated by infra/steering-vectors/inter_channel_cosines.py_",
        "",
        "## Method",
        "",
        f"- Channels: {len(available)} ({', '.join(available)})",
        f"- Layers: {common_layers}",
        "",
        "Cosine = (a · b) / (|a| · |b|). Channels are normalised CAA vectors at the",
        "named transformer layer. Range: -1 (anti-aligned) to +1 (parallel); 0 = orthogonal.",
        "",
        "Threshold convention for multi-channel composition:",
        "- `|cos| < 0.10` — effectively orthogonal; channels compose additively without interference",
        "- `0.10 ≤ |cos| < 0.30` — mild overlap; expected when traits share a coarse axis",
        "- `|cos| ≥ 0.30` — substantial overlap; composition is non-additive (one channel partially activates another)",
        "",
    ]

    # Pre-compute all cosines for the flat top-overlaps section
    flat_overlaps = []  # list of (layer, a, b, cos)

    for L in common_layers:
        # Build matrix
        lines.append(f"## Layer {L}")
        lines.append("")
        header = "| | " + " | ".join(available) + " |"
        sep = "|---|" + "|".join(["---"] * len(available)) + "|"
        lines.append(header)
        lines.append(sep)
        for a in available:
            row_cells = [a]
            for b in available:
                if L not in vectors[a] or L not in vectors[b]:
                    row_cells.append("—")
                    continue
                cos = cosine(vectors[a][L], vectors[b][L])
                if a == b:
                    row_cells.append("1.000")
                else:
                    row_cells.append(f"{cos:+.3f}")
                    if a < b:  # avoid duplicating (a,b) and (b,a)
                        flat_overlaps.append((L, a, b, cos))
            lines.append("| " + " | ".join(row_cells) + " |")
        lines.append("")

    # Top overlaps (sorted by abs cosine, descending) across all layers
    flat_overlaps.sort(key=lambda r: abs(r[3]), reverse=True)
    lines += [
        "## Top inter-channel overlaps (any layer)",
        "",
        "Sorted by `|cosine|` descending. Flag = `|cos| ≥ 0.30`.",
        "",
        "| Layer | Channel A | Channel B | Cosine | \\|Cosine\\| | Flag |",
        "|---|---|---|---|---|---|",
    ]
    for L, a, b, cos in flat_overlaps[:30]:
        flag = "**FLAG**" if abs(cos) >= 0.30 else ("watch" if abs(cos) >= 0.10 else "")
        lines.append(f"| {L} | {a} | {b} | {cos:+.4f} | {abs(cos):.4f} | {flag} |")

    # Channel-level summary: max abs cosine each channel reaches against any other
    lines += [
        "",
        "## Per-channel max |cosine| (worst overlap with any other channel, any layer)",
        "",
        "| Channel | Worst partner | Layer | Cosine | \\|Cosine\\| |",
        "|---|---|---|---|---|",
    ]
    per_channel_worst = {}
    for L, a, b, cos in flat_overlaps:
        for ch, partner in ((a, b), (b, a)):
            if ch not in per_channel_worst or abs(cos) > per_channel_worst[ch][3]:
                per_channel_worst[ch] = (partner, L, cos, abs(cos))
    for ch in available:
        if ch in per_channel_worst:
            partner, L, cos, abs_cos = per_channel_worst[ch]
            lines.append(f"| {ch} | {partner} | {L} | {cos:+.4f} | {abs_cos:.4f} |")

    lines += [
        "",
        "## Interpretation",
        "",
        "Substrate-paper claim (W7-W8): non-orthogonal channel directions blunt multi-channel",
        "single-shot persona substitution because composite vectors are pulled in a 'diagonal'",
        "direction in residual space rather than activating each channel's per-axis effect cleanly.",
        "",
        "If many pairs are at watch (`|cos| ≥ 0.10`) or above, additive composition is leaky.",
        "If most pairs are SAFE (`|cos| < 0.10`), the composition limit is from another source",
        "(e.g. layer-specific saturation, coefficient sensitivity, or persona-prior dominance).",
        "",
        "## Provenance",
        "",
        f"- Vectors directory: {args.vectors_dir}",
        f"- Channels: {', '.join(available)}",
    ]

    out_text = "\n".join(lines)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(out_text)
        print(f"\n✓ wrote {args.out}", file=sys.stderr)
    else:
        print(out_text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
